### PR TITLE
Add policy areas and references to local authority admin

### PR DESCRIPTION
**Pull request by pixeltrix**
### Description of change

Add policy areas and references to local authority admin so that when an officer is adding considerations they can easily look them up.

### Story Link

https://trello.com/c/O4wocZls

### CODE REVIEW

**Comment by pixeltrix** [comment]
southwark bops localhost_3000_admin_policy_areas

**Comment by pixeltrix** [comment]
southwark bops localhost_3000_admin_policy_areas_new

**Comment by pixeltrix** [comment]
southwark bops localhost_3000_admin_policy_references

**Comment by pixeltrix** [comment]
southwark bops localhost_3000_admin_policy_references_new

**Review by cdccollins — APPROVED** [review]

**Pull request merged**
